In [42]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder
from sklearn import preprocessing
import pickle
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn import set_config
import category_encoders as ce
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import FunctionTransformer
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import precision_score, f1_score, confusion_matrix, recall_score


In [2]:
df = pd.read_csv("Loan.csv")

In [3]:
df.head()

Gender Dependents     Education Self_Employed  ApplicantIncome  LoanAmount  \
0   Male          0      Graduate            No             5849         NaN   
1   Male          1      Graduate            No             4583       128.0   
2   Male          0      Graduate           Yes             3000        66.0   
3   Male          0  Not Graduate            No             2583       120.0   
4   Male          0      Graduate            No             6000       141.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df.isna().sum()

Gender             13
Dependents         15
Education           0
Self_Employed      32
ApplicantIncome     0
LoanAmount         22
Credit_History     50
Property_Area       0
Loan_Status         0
dtype: int64

In [5]:
df.isnull().mean()*100

Gender             2.117264
Dependents         2.442997
Education          0.000000
Self_Employed      5.211726
ApplicantIncome    0.000000
LoanAmount         3.583062
Credit_History     8.143322
Property_Area      0.000000
Loan_Status        0.000000
dtype: float64

In [6]:
list = [col for col in df.columns if df[col].isnull().mean() <0.03 and df[col].isnull().mean()>0]
list

['Gender', 'Dependents']

In [7]:
df.dropna(subset = list[0:2], inplace = True)

In [8]:
df.isnull().mean()*100

Gender             0.000000
Dependents         0.000000
Education          0.000000
Self_Employed      5.460751
ApplicantIncome    0.000000
LoanAmount         3.412969
Credit_History     8.361775
Property_Area      0.000000
Loan_Status        0.000000
dtype: float64

In [9]:
imp1=SimpleImputer(strategy="median")
imp2=SimpleImputer(strategy="most_frequent")

In [10]:
df.head(3)

Gender Dependents Education Self_Employed  ApplicantIncome  LoanAmount  \
0   Male          0  Graduate            No             5849         NaN   
1   Male          1  Graduate            No             4583       128.0   
2   Male          0  Graduate           Yes             3000        66.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y

In [11]:
tr=ColumnTransformer([
                    ('Median',imp1,['LoanAmount']),
                    ('Mode',imp2,[0, 1, 3, 6]),
                    ],
                     remainder='passthrough')

In [12]:
df = tr.fit_transform(df)

In [13]:
df

array([[127.0, 'Male', '0', ..., 5849, 'Urban', 'Y'],
       [128.0, 'Male', '1', ..., 4583, 'Rural', 'N'],
       [66.0, 'Male', '0', ..., 3000, 'Urban', 'Y'],
       ...,
       [253.0, 'Male', '1', ..., 8072, 'Urban', 'Y'],
       [187.0, 'Male', '2', ..., 7583, 'Urban', 'Y'],
       [133.0, 'Female', '0', ..., 4583, 'Semiurban', 'N']], dtype=object)

In [14]:
df = pd.DataFrame(df)

In [15]:
df.isnull().mean()*100

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
dtype: float64

In [16]:
df

0       1   2    3    4             5     6          7  8
0    127.0    Male   0   No  1.0      Graduate  5849      Urban  Y
1    128.0    Male   1   No  1.0      Graduate  4583      Rural  N
2     66.0    Male   0  Yes  1.0      Graduate  3000      Urban  Y
3    120.0    Male   0   No  1.0  Not Graduate  2583      Urban  Y
4    141.0    Male   0   No  1.0      Graduate  6000      Urban  Y
..     ...     ...  ..  ...  ...           ...   ...        ... ..
581   71.0  Female   0   No  1.0      Graduate  2900      Rural  Y
582   40.0    Male  3+   No  1.0      Graduate  4106      Rural  Y
583  253.0    Male   1   No  1.0      Graduate  8072      Urban  Y
584  187.0    Male   2   No  1.0      Graduate  7583      Urban  Y
585  133.0  Female   0  Yes  0.0      Graduate  4583  Semiurban  N

[586 rows x 9 columns]

In [17]:
## Encoding

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

# Define the transformation
trf1 = ColumnTransformer(
    transformers=[
        ('ohe_Gender', OneHotEncoder(handle_unknown='ignore'), [1, 3, 2, 5]),
        ('ordinal_Propertyarea', OrdinalEncoder(categories=[['Rural', 'Urban', 'Semiurban']]), [7]),
        
    ],
    remainder='passthrough')


In [19]:
df = trf1.fit_transform(df)

In [20]:
df

array([[0.0, 1.0, 1.0, ..., 1.0, 5849, 'Y'],
       [0.0, 1.0, 1.0, ..., 1.0, 4583, 'N'],
       [0.0, 1.0, 0.0, ..., 1.0, 3000, 'Y'],
       ...,
       [0.0, 1.0, 1.0, ..., 1.0, 8072, 'Y'],
       [0.0, 1.0, 1.0, ..., 1.0, 7583, 'Y'],
       [1.0, 0.0, 0.0, ..., 0.0, 4583, 'N']], dtype=object)

In [21]:
df = pd.DataFrame(df)

In [22]:
df.head(2)

0    1    2    3    4    5    6    7    8    9    10     11   12    13 14
0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  127.0  1.0  5849  Y
1  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  128.0  1.0  4583  N

In [23]:
label_encoder = preprocessing.LabelEncoder()
df[14] = label_encoder.fit_transform(df[14])
df[14].unique()

array([1, 0])

In [24]:
df.head(5)

0    1    2    3    4    5    6    7    8    9    10     11   12    13  14
0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  127.0  1.0  5849   1
1  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  128.0  1.0  4583   0
2  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0   66.0  1.0  3000   1
3  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  120.0  1.0  2583   1
4  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  141.0  1.0  6000   1

In [25]:
trf2 = ColumnTransformer([
    ('scale',MinMaxScaler(), [0,1,2,3,4,5,6,7,8,9,10,12]),
    ('scale2',StandardScaler(), [11, 13]),
],     remainder='passthrough')

In [26]:
df = trf2.fit_transform(df)

In [27]:
df

array([[ 0.        ,  1.        ,  1.        , ..., -0.21708158,
         0.0939562 ,  1.        ],
       [ 0.        ,  1.        ,  1.        , ..., -0.20486631,
        -0.12255573,  0.        ],
       [ 0.        ,  1.        ,  0.        , ..., -0.96221297,
        -0.39328114,  1.        ],
       ...,
       [ 0.        ,  1.        ,  1.        , ...,  1.32204226,
         0.47413472,  1.        ],
       [ 0.        ,  1.        ,  1.        , ...,  0.51583453,
         0.39050571,  1.        ],
       [ 1.        ,  0.        ,  0.        , ..., -0.14378997,
        -0.12255573,  0.        ]])

In [28]:
df = pd.DataFrame(df)

In [29]:
df

0    1    2    3    4    5    6    7    8    9    10   11        12  \
0    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.217082   
1    0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0 -0.204866   
2    0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.962213   
3    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.5  1.0 -0.302588   
4    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.046068   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
581  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0 -0.901137   
582  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0 -1.279810   
583  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.5  1.0  1.322042   
584  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.5  1.0  0.515835   
585  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0 -0.143790   

           13   14  
0    0.093956  1.0  
1   -0.122556  0.0  
2   -0.393281  1.0  
3   -0.464597  1.0  
4    0.119780  1.0  
..        ...  ...  
581 -0.410383  1.0  
582 -0.204132  1.0  
583  0.474135  1.0  
584  0.390506  1.0  
585 -0.122556  0.0  

[586 rows x 15 columns]

In [30]:
df[14].unique()

array([1., 0.])

In [31]:
X = df.drop(columns = [14], axis = 1)

In [32]:
y = df[14]

In [33]:
X

0    1    2    3    4    5    6    7    8    9    10   11        12  \
0    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.217082   
1    0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0 -0.204866   
2    0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.962213   
3    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.5  1.0 -0.302588   
4    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.046068   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
581  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0 -0.901137   
582  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0 -1.279810   
583  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.5  1.0  1.322042   
584  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.5  1.0  0.515835   
585  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0 -0.143790   

           13  
0    0.093956  
1   -0.122556  
2   -0.393281  
3   -0.464597  
4    0.119780  
..        ...  
581 -0.410383  
582 -0.204132  
583  0.474135  
584  0.390506  
585 -0.122556  

[586 rows x 14 columns]

In [34]:
y

0      1.0
1      0.0
2      1.0
3      1.0
4      1.0
      ... 
581    1.0
582    1.0
583    1.0
584    1.0
585    0.0
Name: 14, Length: 586, dtype: float64

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.8,random_state=1)

In [60]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(penalty='l2', C=1.0)


In [62]:
log_reg.fit(X_train, y_train)

LogisticRegression()

In [63]:
predictions = log_reg.predict(X_test)

In [64]:
accuracy = log_reg.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7825159914712153


In [65]:
# Calculate precision
precision = precision_score(y_test, predictions, average='weighted')
print("Precision:", precision)



Precision: 0.7746415315711691


In [66]:
# Calculate F1-score
f1 = f1_score(y_test, predictions, average='weighted')
print("F1 Score:", f1)

F1 Score: 0.766383181495122


In [67]:
# Calculate recall
recall = recall_score(y_test, predictions, average='weighted')
print("Recall:", recall)

Recall: 0.7825159914712153


In [68]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(log_reg, X_train, y_train, cv=5, scoring='accuracy')

array([0.75      , 0.70833333, 0.7826087 , 0.73913043, 0.86956522])

In [69]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(log_reg, X_train, y_train, cv=5, scoring='accuracy').mean()

0.769927536231884

In [70]:
## Grid Search CV

In [80]:
# gridsearchcv
param_grid = {
    "penalty": ['l1', 'l2'],
    "C": [0.001, 0.01, 0.1, 1, 10, 100]
}


In [82]:
# log_reg.get_params().keys()

In [81]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(log_reg, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

/Users/sid24082/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/sid24082/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/sid24082/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/Users/sid24082/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logisti

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2']},
             scoring='accuracy')

In [83]:
grid.best_score_

0.769927536231884

In [84]:
grid.best_params_

{'C': 1, 'penalty': 'l2'}

In [86]:
# export 
import pickle
pickle.dump(log_reg,open('pipe.pkl','wb'))

In [88]:
lr_pipe = pickle.load(open('pipe.pkl','rb'))

In [89]:
X

0    1    2    3    4    5    6    7    8    9    10   11        12  \
0    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.217082   
1    0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0 -0.204866   
2    0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.962213   
3    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.5  1.0 -0.302588   
4    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.5  1.0 -0.046068   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
581  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0 -0.901137   
582  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0 -1.279810   
583  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.5  1.0  1.322042   
584  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.5  1.0  0.515835   
585  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0 -0.143790   

           13  
0    0.093956  
1   -0.122556  
2   -0.393281  
3   -0.464597  
4    0.119780  
..        ...  
581 -0.410383  
582 -0.204132  
583  0.474135  
584  0.390506  
585 -0.122556  

[586 rows x 14 columns]

In [92]:
test_data =np.array([[0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0,0.0, 0.5, 1.0, -0.962213, 0.093956]],dtype=object).reshape(1,14)

In [93]:
lr_pipe.predict(test_data)

array([1.])